### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by saifulfrank** [michaelheiniger/PhoneCallNotifier#1]
Hi
I want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by michaelheiniger** [comment]
Hi,
Sure, sounds good! I have no requirement so feel free to be creative ;-)

**Comment by michaelheiniger** [comment]
Hi, 
I like them all. If it's not too much work, could you modify the first one such that there is only the bottom (red) part ?`Since the app is only used to notify and reject blacklisted numbers (there is no whitelist numbers).

Thanks !

**Comment by saifulfrank** [comment]
great! check it now.
![call notify](https://user-images.githubusercontent.com/37498811/44170226-82b47c00-a0f8-11e8-9403-029668d473b3.png)

which one you want to add on readme. Let me know please

**Comment by michaelheiniger** [comment]
Awesome, thanks ! I'll use the one.

**Comment by saifulfrank** [comment]
Here is google drive link. You will find all launcher icon and editable source files and other necessary files there
<a href="https://drive.google.com/open?id=12AWTSANQEO0v6upAuyogrihjJ9lmWCPp">Download</a>
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>

**Comment by saifulfrank** [comment]
please check pull #3 
Thank you

**Comment by michaelheiniger** [comment]
I've added the logo to the app. Thanks again !
Cheers
